package com.kntro.reqsai.discovery.interfaces.rest.swagger;

import com.kntro.reqsai.discovery.interfaces.rest.dto.response.UserStoryResponse;
import com.kntro.reqsai.shared.interfaces.pagination.PageResponse;
import com.kntro.reqsai.shared.infrastructure.configuration.ApiVersioning;
import com.kntro.reqsai.shared.infrastructure.documentation.openapi.OpenApiConfiguration;
import com.kntro.reqsai.shared.infrastructure.documentation.openapi.annotations.ApiResponseNotFound;
import com.kntro.reqsai.shared.infrastructure.documentation.openapi.annotations.ApiStandardErrorResponses;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.UUID;

/**
 * API contract for session-scoped user story endpoints; implemented by {@code controllers.SessionStoryControllerImpl}.
 * Covers AI-generated stories reviewed in the context of the session that produced them.
 * Manual stories (no {@code sessionId}) are not visible here — use {@code ProjectStoryController} instead.
 */
@RequestMapping(path = ApiVersioning.BASE + "/sessions/{sessionId}/stories", produces = MediaType.APPLICATION_JSON_VALUE)
@Tag(name = "Session Stories", description = "User stories generated by a discovery session — review, approve, or reject them here")
public interface SessionStoryController {

    @Operation(
            summary = "Get a session story by id",
            description = """
                    Returns a single user story that was generated by the given discovery session. \
                    Stories that were created manually (no `sessionId`) are not accessible from this scope — \
                    use `GET /api/projects/{projectId}/stories/{storyId}` for those.""")
    @ApiResponse(
            responseCode = "200",
            description = "Story found",
            content = @Content(
                    mediaType = MediaType.APPLICATION_JSON_VALUE,
                    schema = @Schema(implementation = UserStoryResponse.class)))
    @ApiResponseNotFound
    @ApiStandardErrorResponses
    @SecurityRequirement(name = OpenApiConfiguration.BEARER_SCHEME)
    @GetMapping(path = "/{storyId}", version = ApiVersioning.V1)
    ResponseEntity<UserStoryResponse> getById(
            @Parameter(description = "Session that generated the story", required = true)
            @PathVariable UUID sessionId,
            @Parameter(description = "Story identifier", required = true)
            @PathVariable UUID storyId);

    @Operation(
            summary = "List stories generated by a session",
            description = "Returns a paginated list of user stories that were generated by the given discovery session, scoped to the authenticated tenant.")
    @ApiResponse(
            responseCode = "200",
            description = "Paginated list of session stories",
            content = @Content(mediaType = MediaType.APPLICATION_JSON_VALUE))
    @ApiResponseNotFound
    @ApiStandardErrorResponses
    @SecurityRequirement(name = OpenApiConfiguration.BEARER_SCHEME)
    @GetMapping(version = ApiVersioning.V1)
    ResponseEntity<PageResponse<UserStoryResponse>> list(
            @Parameter(description = "Session whose stories to list", required = true)
            @PathVariable UUID sessionId,
            @Parameter(description = "Zero-based page index", example = "0")
            @RequestParam(required = false) Integer page,
            @Parameter(description = "Page size (max 100)", example = "20")
            @RequestParam(required = false) Integer size,
            @Parameter(description = "Sort field: createdAt | title | priority | status", example = "createdAt")
            @RequestParam(required = false) String sortBy,
            @Parameter(description = "Sort direction: ASC | DESC", example = "DESC")
            @RequestParam(required = false) String sortDirection);
}
