spring:
  ai:
    model:
      chat: ollama
      embedding: ollama
      audio:
        transcription: openai

reqsai:
  ai:
    stt:
      provider: whisper
    generation:
      provider: gemini
    embedding:
      provider: auto
