package com.kntro.reqsai.discovery.application.query;

import com.kntro.reqsai.shared.interfaces.pagination.PageCriteria;

import java.util.UUID;

/** Query to list the user stories generated by a specific discovery session. */
public record ListSessionStoriesQuery(UUID sessionId, PageCriteria criteria) {
}
